---
name: Test Simple Shell Action

'on':
  push:
    branches: [main, copilot/fix-3]
  pull_request:
    branches: [main]

jobs:
  test-shell-action:
    runs-on: ubuntu-latest
    name: Test shell action
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test shell action
        uses: ./shell-hello
        with:
          who-to-greet: 'GitHub Actions'
        id: hello

      - name: Get the output
        run: echo "Output was ${{ steps.hello.outputs.greeting }}"
  ci:
    name: CI
    runs-on: ubuntu-latest
    if: always()
    needs:
      - test-shell-action
    steps:
      - name: Check results
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        run: exit 1
